[package]
name = "shorten-url"
version = "0.1.0"
authors = ["Ren√©e Kooi <renee@kooi.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.3.3"
